sudo: required
dist: trusty

services:
- docker

language: java
jdk:
- oraclejdk8

before_install:
- if [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    openssl aes-256-cbc -K $encrypted_7e6e282fecc8_key -iv $encrypted_7e6e282fecc8_iv -in travis/resources/servicekey.json.enc -out servicekey.json -d;
  fi

script:
- travis_wait 180 travis/test.sh
