sudo: required
dist: trusty

services:
- docker

language: java
jdk:
- oraclejdk8

before_install:
- if [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    openssl aes-256-cbc -K $encrypted_7e6e282fecc8_key -iv $encrypted_7e6e282fecc8_iv -in travis/resources/servicekey.json.enc -out servicekey.json -d;
  fi

script:
- # Sleep one minute between printouts, but don't zombie for more than two hours. This prevents Travis from automatically exiting due to lack of output while workflow is running.
  for ((i=0; i < 180; i++)); do
      sleep 60
      printf "…"${i}
  done &
- travis/test.sh
#If travis/test.sh hasn't completed wait for 60min
- if [ $test_complete == false ]; then
     sleep 60m
  fi
- if [ $test_complete == false ]; then
     sleep 60m
  fi
