sudo: required
dist: trusty
services:
- docker
language: java
jdk:
- oraclejdk8

before_install:

#- if [ $TRAVIS_SECURE_ENV_VARS == true ]; then
-    export BOTO_CONFIG=/dev/null
-    GCLOUD_HOME=$HOME/gcloud/google-cloud-sdk/bin
-    openssl aes-256-cbc -K $encrypted_7e6e282fecc8_key -iv $encrypted_7e6e282fecc8_iv -in travis/resources/servicekey.json.enc -out servicekey.json -d
-    travis/resources/install_gcloud.sh
-    printf 'y\n' | $GCLOUD_HOME/gcloud components update
#    if [[ $TEST_TYPE == cloud ]]; then
#      printf 'y\n' | $GCLOUD_HOME/gcloud components install beta;
#    fi;
-    $GCLOUD_HOME/gcloud config set project broad-dsde-outreach
-    $GCLOUD_HOME/gcloud auth activate-service-account --key-file servicekey.json
-    $GCLOUD_HOME/gcloud info
-    export GOOGLE_APPLICATION_CREDENTIALS="servicekey.json"
#  fi
script:
- travis/test.sh
