sudo: required
dist: trusty
services:
- docker
language: java
jdk:
- oraclejdk8
deploy:
  provider: gae
  keyfile: travis/resources/servicekey.json.enc
  project: broad-dsde-outreach
before_install:
- openssl aes-256-cbc -K $encrypted_7e6e282fecc8_key -iv $encrypted_7e6e282fecc8_iv
  -in travis/resources/servicekey.json.enc -out servicekey.json -d
script:
- travis/test.sh